# Standards: 0.11
---

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Flush ipv4 route
  command: "sysctl -w net.ipv4.route.flush=1"

- name: Restart ntp
  service:
    name: ntp
    state: restarted
