# Standards: 0.11
---

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IP forwarding is disabled
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Get IP forwarding value in active kernel parameters
  command: "cat {{ item.proc_src }}"
  register: v_3_1_1_kernel_param
  with_items:
    - "{{ v_3_1_1_ipv4_ip_forward }}"
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Displaying value
  debug:
    msg: The value for kernel_param_value is {{ v_3_1_1_kernel_param.results[0].stdout }}

- name: 3.1.1 - Ensure IP forwarding is disabled in active kernel parameters
  command: "sysctl -w {{ item.kernel_param }}={{ item.value }}"
  with_items:
    - "{{ v_3_1_1_ipv4_ip_forward }}"
  when: "{{ v_3_1_1_kernel_param.results[0].stdout }} != {{ item.value }}"
  notify: Flush ipv4 route
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored
