# Standards: 0.11
---

# 2.1.1 Ensure chargen services are not enabled

# Chargen is usually installed with xinetd

- name: 2.1.1 - Check to see if xinetd is installed
  yum:
    list: xinetd
  register: is_installed

- name: 2.1.1 - Display installation status of xinetd
  debug:
    msg: Installation Status is {{ is_installed.results[-1].yumstate }}

- name: 2.1.1 - Ensure chargen services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - chargen-dgram
    - chargen-stream
  when:  cis_xinetd_state != 'absent' 
#  ignore_errors: true
  tags:
    - level-1
    - section-2
    - "2.1.1"
    - scored
