# Standards: 0.11
---

# 5.3.2 Ensure lockout for failed password attempts is configured

- name: 5.3.2 - Ensure lockout for failed password attempts is configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored
    - todo
